In [2]:
import pandas as pd
import numpy as np
import time
from dask import dataframe as df
  
# time taken to read data
s_time_dask = time.time()
dask_df = df.read_csv('original_dataset/test_data.csv')
e_time_dask = time.time()
  
print("Read with dask: ", (e_time_dask-s_time_dask), "seconds")
# data
dask_df.head(10)

Read with dask:  0.05285906791687012 seconds

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-02-19,0.631315,0.001912,0.010728,0.814497,0.007547,0.168651,0.009971,0.002347,...,NaN,NaN,NaN,NaN,0.004669,NaN,NaN,NaN,0.008281,NaN
1,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-03-25,0.587042,0.005275,0.011026,0.810848,0.001817,0.241389,0.000166,0.009132,...,NaN,NaN,NaN,0.000142,0.004940,0.009021,NaN,0.003695,0.003753,0.001460
2,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-04-25,0.609056,0.003326,0.016390,1.004620,0.000114,0.266976,0.004196,0.004192,...,NaN,NaN,NaN,0.000074,0.002114,0.004656,NaN,0.003155,0.002156,0.006482
3,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-05-20,0.614911,0.009065,0.021672,0.816549,0.009722,0.188947,0.004123,0.015325,...,NaN,NaN,NaN,0.004743,0.006392,0.002890,NaN,0.006044,0.005206,0.007855
4,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-06-15,0.591673,0.238794,0.015923,0.810456,0.002026,0.180035,0.000731,0.011281,...,NaN,NaN,NaN,0.008133,0.004329,0.008384,NaN,0.001008,0.007421,0.009471
5,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-07-13,0.587472,0.005827,0.007959,1.001009,0.008814,0.173701,0.000653,0.009779,...,NaN,NaN,NaN,0.007001,0.003962,0.005530,NaN,0.009870,0.009667,0.005398
6,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-08-16,0.625006,0.238704,0.013420,0.816605,0.009849,0.170644,0.002495,0.019999,...,NaN,NaN,NaN,0.001132,0.007676,0.005410,NaN,0.006762,0.005664,0.002627
7,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-09-29,0.597074,0.003537,0.017426,1.000670,0.005143,0.158006,0.000985,0.011962,...,NaN,NaN,NaN,0.008730,0.000628,0.002821,NaN,0.004141,0.005733,0.005657
8,00000469ba478561f23a92a868bd366de6f6527a684c9a...,2019-10-12,0.568930,0.121385,0.010779,1.009347,0.006923,0.149413,0.000396,0.003576,...,NaN,NaN,NaN,0.005912,0.001250,0.006543,NaN,0.009160,0.003690,0.003219
9,00001bf2e77ff879fab36aa4fac689b9ba411dae63ae39...,2018-04-22,0.894195,0.325657,0.020970,1.001803,0.005125,0.073243,0.005347,0.001597,...,NaN,NaN,NaN,0.008065,0.009861,0.009535,NaN,0.003964,0.008436,0.008323

In [3]:
df_train = dask_df

In [4]:
df_train = df_train.drop(['S_2'],axis = 1)

In [5]:
df_train.head(5)

,customer_ID,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.631315,0.001912,0.010728,0.814497,0.007547,0.168651,0.009971,0.002347,0.113189,...,NaN,NaN,NaN,NaN,0.004669,NaN,NaN,NaN,0.008281,NaN
1,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.587042,0.005275,0.011026,0.810848,0.001817,0.241389,0.000166,0.009132,0.123035,...,NaN,NaN,NaN,0.000142,0.004940,0.009021,NaN,0.003695,0.003753,0.001460
2,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.609056,0.003326,0.016390,1.004620,0.000114,0.266976,0.004196,0.004192,0.125319,...,NaN,NaN,NaN,0.000074,0.002114,0.004656,NaN,0.003155,0.002156,0.006482
3,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.614911,0.009065,0.021672,0.816549,0.009722,0.188947,0.004123,0.015325,0.123439,...,NaN,NaN,NaN,0.004743,0.006392,0.002890,NaN,0.006044,0.005206,0.007855
4,00000469ba478561f23a92a868bd366de6f6527a684c9a...,0.591673,0.238794,0.015923,0.810456,0.002026,0.180035,0.000731,0.011281,0.122212,...,NaN,NaN,NaN,0.008133,0.004329,0.008384,NaN,0.001008,0.007421,0.009471

In [6]:
#df_train = dask_df.groupby(["customer_ID"]).tail(1).set_index("customer_ID")

AttributeError: 'Column not found: tail'

In [7]:
df_train = df_train[['S_3', 'S_5', 'S_6', 'S_7', 'S_8', 'S_11', 'S_12', 'S_13', 'S_15',
       'S_16', 'S_22', 'S_23', 'S_24', 'S_25', 'S_27','R_1', 'R_2', 'R_3', 'R_4', 'R_5', 'R_6', 'R_7', 'R_8', 'R_9', 'R_10',
       'R_12', 'R_13', 'R_24', 'R_26', 'R_27','B_1', 'B_2', 'B_3', 'B_4', 'B_6', 'B_7', 'B_9', 'B_10', 'B_11', 'B_14',
       'B_16', 'B_17', 'B_18', 'B_19', 'B_20', 'B_22', 'B_23', 'B_25', 'B_33',
       'B_37', 'B_38', 'B_40','D_39', 'D_41', 'D_44', 'D_47', 'D_48', 'D_51', 'D_54', 'D_55', 'D_58',
       'D_61', 'D_62', 'D_70', 'D_74', 'D_75', 'D_78', 'D_112','P_2','P_3','P_4']]

In [8]:
df_train = df_train.round(3)

In [9]:
df_train.head(10)

,S_3,S_5,S_6,S_7,S_8,S_11,S_12,S_13,S_15,S_16,...,D_61,D_62,D_70,D_74,D_75,D_78,D_112,P_2,P_3,P_4
0,0.169,0.003,1.007,0.106,0.322,1.882,0.191,0.409,0.401,0.003,...,0.589,0.052,NaN,0.218,0.205,0.004,1.004,0.631,NaN,0.960
1,0.241,0.006,1.006,0.161,0.171,2.043,0.190,0.561,0.606,0.007,...,0.623,0.058,0.001,0.217,0.207,0.002,1.004,0.587,NaN,0.962
2,0.267,0.003,0.006,0.210,0.173,1.642,-0.026,0.692,0.602,0.007,...,0.618,0.051,0.002,0.223,0.205,0.008,1.004,0.609,NaN,0.964
3,0.189,0.007,0.006,0.194,0.171,1.002,0.097,0.691,0.508,0.004,...,0.614,0.015,0.000,0.217,0.203,0.004,1.003,0.615,NaN,0.959
4,0.180,0.009,0.003,0.202,0.320,1.082,0.117,0.692,0.402,0.004,...,0.593,0.020,0.006,0.215,0.201,0.006,1.004,0.592,0.598,0.963
5,0.174,0.001,0.000,0.184,0.176,1.764,0.288,0.689,0.508,0.010,...,0.588,0.017,0.006,0.222,0.203,0.003,1.003,0.587,0.535,0.960
6,0.171,0.010,0.007,0.148,0.324,1.564,-0.003,0.558,0.402,0.006,...,0.586,0.022,0.007,0.222,0.202,0.002,1.004,0.625,0.632,0.964
7,0.158,0.010,0.005,0.169,0.320,1.727,0.190,0.564,0.410,0.004,...,0.578,0.035,0.007,0.223,0.210,0.006,1.003,0.597,0.634,0.959
8,0.149,0.012,0.003,0.160,0.464,1.767,0.188,0.556,0.300,0.009,...,0.589,0.049,0.007,0.217,0.202,0.002,1.007,0.569,0.561,0.965
9,0.073,0.032,0.002,0.045,0.761,0.161,0.184,0.284,0.104,0.002,...,0.076,0.329,0.009,0.004,0.004,0.008,1.006,0.894,0.589,0.010

In [10]:
df_train.head(5)

,S_3,S_5,S_6,S_7,S_8,S_11,S_12,S_13,S_15,S_16,...,D_61,D_62,D_70,D_74,D_75,D_78,D_112,P_2,P_3,P_4
0,0.169,0.003,1.007,0.106,0.322,1.882,0.191,0.409,0.401,0.003,...,0.589,0.052,NaN,0.218,0.205,0.004,1.004,0.631,NaN,0.960
1,0.241,0.006,1.006,0.161,0.171,2.043,0.190,0.561,0.606,0.007,...,0.623,0.058,0.001,0.217,0.207,0.002,1.004,0.587,NaN,0.962
2,0.267,0.003,0.006,0.210,0.173,1.642,-0.026,0.692,0.602,0.007,...,0.618,0.051,0.002,0.223,0.205,0.008,1.004,0.609,NaN,0.964
3,0.189,0.007,0.006,0.194,0.171,1.002,0.097,0.691,0.508,0.004,...,0.614,0.015,0.000,0.217,0.203,0.004,1.003,0.615,NaN,0.959
4,0.180,0.009,0.003,0.202,0.320,1.082,0.117,0.692,0.402,0.004,...,0.593,0.020,0.006,0.215,0.201,0.006,1.004,0.592,0.598,0.963

Dask DataFrame Structure:
                      S_3      S_5      S_6      S_7      S_8     S_11     S_12     S_13     S_15     S_16     S_22     S_23     S_24     S_25     S_27      R_1      R_2      R_3      R_4      R_5      R_6      R_7      R_8      R_9     R_10     R_12     R_13     R_24     R_26     R_27      B_1      B_2      B_3      B_4      B_6      B_7      B_9     B_10     B_11     B_14     B_16     B_17     B_18     B_19     B_20     B_22     B_23     B_25     B_33     B_37     B_38     B_40     D_39     D_41     D_44     D_47     D_48     D_51     D_54     D_55     D_58     D_61     D_62     D_70     D_74     D_75     D_78    D_112      P_2      P_3      P_4
npartitions=1008
                  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64
                      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
...                   ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
                      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
                      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
Dask Name: round, 4032 tasks

In [68]:
df_train = df_train.compute()

MemoryError: Unable to allocate 6.01 GiB for an array with shape (71, 11363762) and data type float64

In [67]:
df_train.reset_index(drop=True,inplace =True)

TypeError: reset_index() got an unexpected keyword argument 'inplace'

In [ ]:
df_train

In [ ]:
from sklearn.impute import SimpleImputer
numeric_data = df_train.select_dtypes(include=[np.number])
categorical_data = df_train.select_dtypes(exclude=[np.number])

numeric_data.shape[1]
categorical_data.shape[1]
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(numeric_data)
numeric_columns =df_train.select_dtypes(np.number).columns
df_train[numeric_columns] = df_train[numeric_columns].fillna(df_train[numeric_columns].mean())
df_train[numeric_columns] = df_train[numeric_columns].round(3)
df_train.isna().sum()

In [ ]:
import joblib
import pickle
filename = "Completed_model.joblib"
loaded_model = joblib.load(filename)
result = loaded_model.predict(df_train)
print(result)